"""Add is_free field to listings for free giveaways

Revision ID: 4bbe65ae41a3
Revises: ae4626c214eb
Create Date: 2025-12-14 15:40:30.981573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbe65ae41a3'
down_revision = 'ae4626c214eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_listings_is_free'), ['is_free'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_is_free'))
        batch_op.drop_column('is_free')

    # ### end Alembic commands ###
