"""Add email verification

Revision ID: 6b38e0fb7bf4
Revises: af76f09a25fd
Create Date: 2025-12-08 18:54:00.280647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b38e0fb7bf4'
down_revision = 'af76f09a25fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before creating (for SQLite compatibility)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if email_verifications table exists
    if 'email_verifications' not in inspector.get_table_names():
        op.create_table('email_verifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('verification_code', sa.String(length=6), nullable=False),
        sa.Column('display_name', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('email_verifications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_email_verifications_email'), ['email'], unique=False)
            batch_op.create_index(batch_op.f('ix_email_verifications_expires_at'), ['expires_at'], unique=False)
    
    # Check users table columns
    users_columns = [col['name'] for col in inspector.get_columns('users')]
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'email_verified' not in users_columns:
            batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_expires_at'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_email'))

    op.drop_table('email_verifications')
    # ### end Alembic commands ###
