"""Add unique username field to users and email_verifications

Revision ID: ae4626c214eb
Revises: 6b38e0fb7bf4
Create Date: 2025-12-12 01:10:37.917047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4626c214eb'
down_revision = '6b38e0fb7bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add username column to email_verifications (nullable first, then update)
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=True))
    
    # Update existing email_verifications with placeholder username
    op.execute("UPDATE email_verifications SET username = 'user_' || CAST(id AS TEXT) WHERE username IS NULL")

    # Make username NOT NULL for email_verifications
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)

    # Add username column to users (nullable)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=True))
    
    # Create usernames for existing users based on display_name or email
    connection = op.get_bind()
    try:
        result = connection.execute(sa.text("SELECT id, display_name, email FROM users WHERE username IS NULL"))
        users = result.fetchall()
        
        for user_id, display_name, email in users:
            # Create base username from display_name or email
            base_username = (display_name or email.split('@')[0]).lower()
            # Remove invalid characters
            base_username = ''.join(c if c.isalnum() or c == '_' else '_' for c in base_username)
            # Ensure it starts with a letter or number
            if not base_username or not (base_username[0].isalnum() if base_username else False):
                base_username = 'user_' + base_username if base_username else 'user'
            # Limit length
            base_username = base_username[:27]  # Leave room for counter
            
            username = base_username
            counter = 1
            # Check if username exists and find unique one
            while True:
                existing = connection.execute(
                    sa.text("SELECT id FROM users WHERE username = :username"),
                    {"username": username}
                ).fetchone()
                if not existing:
                    break
                username = f"{base_username}_{counter}"[:30]
                counter += 1
            
            # Update user with unique username
            connection.execute(
                sa.text("UPDATE users SET username = :username WHERE id = :user_id"),
                {"username": username, "user_id": user_id}
            )
    except Exception:
        # If there are no users or any error, just continue
        pass
    
    # Create unique index
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('username')

    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
