"""Add region, MFA fields to User and expires_at to Listing

Revision ID: af76f09a25fd
Revises: 5801370878a1
Create Date: 2025-12-08 15:31:06.990425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af76f09a25fd'
down_revision = '5801370878a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding them (for SQLite compatibility)
    conn = op.get_bind()
    
    # Check listings table
    inspector = sa.inspect(conn)
    listings_columns = [col['name'] for col in inspector.get_columns('listings')]
    
    with op.batch_alter_table('listings', schema=None) as batch_op:
        if 'expires_at' not in listings_columns:
            batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
            batch_op.create_index(batch_op.f('ix_listings_expires_at'), ['expires_at'], unique=False)
        elif 'ix_listings_expires_at' not in [idx['name'] for idx in inspector.get_indexes('listings')]:
            batch_op.create_index('ix_listings_expires_at', ['expires_at'], unique=False)

    # Check users table
    users_columns = [col['name'] for col in inspector.get_columns('users')]
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'region' not in users_columns:
            batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True, server_default='israel'))
        if 'mfa_enabled' not in users_columns:
            batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default='0'))
        if 'mfa_secret' not in users_columns:
            batch_op.add_column(sa.Column('mfa_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('region')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_expires_at'))
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
